### ISSUE TITLE
打包不支持多层目录

### ISSUE THREAD

**Issue by hackchen01** [chjtx/JTaro-Bundle#1]
打包不支持多层目录，比如 pages/aaa/aaa是不支持的，如果使用多目录会报JTaroLoader is not defined错误，请修正

**Comment by chjtx** [comment]
@hackchen01 能把你的项目结构贴出来看看吗？或者给个仓库地址

**Comment by hackchen01** [comment]
![image](https://user-images.githubusercontent.com/28593348/34764502-b3f4416c-f629-11e7-8814-b3b8bb809a88.png)
打包后是不带news目录里面的文件的

**Comment by chjtx** [comment]
是的，这个脚本只会`将整个文件夹所有第一层js文件（Vue页面组件）合并到一个文件并创建Vue组件`，不会递归遍历所有子文件夹，如果第一层js文件没引用子文件夹里的内容，将不会打包
